/* eslint-disable */
// ⚠️ ARCHIVO GENERADO — no editar a mano.
//
// Sale de `docs/04-diseno/inventario-de-pantallas.md`, que es la autoridad sobre qué
// pantallas existen. Para regenerarlo: `npm run generar-inventario`.
//
// `npm run verificar` falla si este archivo quedó atrás respecto del documento.

import type { PantallaInventariada } from './tipos';

/** Las 138 pantallas del inventario, en el orden en que el documento las lista. */
export const INVENTARIO: readonly PantallaInventariada[] = [
  {id:"PT-001",nombre:"Ingreso y selección de puesto vigente",cliente:"A",roles:"todos",cu:"—",hu:"—",sinRed:"No",papel:"No",seccion:"2.1 Transversales"},
  {id:"PT-002",nombre:"Inicio del puesto: pendientes, alertas y accesos",cliente:"A",roles:"todos",cu:"—",hu:"—",sinRed:"No",papel:"No",seccion:"2.1 Transversales"},
  {id:"PT-003",nombre:"Bandeja de tareas escaladas por segregación de funciones",cliente:"A",roles:"ACT-03 ACT-04 ACT-08",cu:"CU-02, CU-06",hu:"HU-010",sinRed:"No",papel:"No",seccion:"2.1 Transversales"},
  {id:"PT-004",nombre:"Patrón de pantalla de bloqueo duro: qué se impidió, por qué, cómo salir",cliente:"A/C",roles:"todos",cu:"CU-02, CU-04, CU-06, CU-15",hu:"HU-010, HU-025, HU-039, HU-077, HU-078, HU-091, HU-108",sinRed:"Sí",papel:"No",seccion:"2.1 Transversales"},
  {id:"PT-005",nombre:"Buscador de expedientes con alcance de datos aplicado",cliente:"A",roles:"todos",cu:"—",hu:"—",sinRed:"No",papel:"No",seccion:"2.1 Transversales"},
  {id:"PT-006",nombre:"Mis solicitudes",cliente:"A",roles:"ACT-02",cu:"CU-01",hu:"HU-001",sinRed:"No",papel:"No",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-007",nombre:"Requisición de vehículo (solicitud de transporte)",cliente:"A",roles:"ACT-02",cu:"CU-01",hu:"HU-001, HU-003",sinRed:"No",papel:"Sí",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-008",nombre:"Objeto del traslado: personas, carga o mixto",cliente:"A",roles:"ACT-02",cu:"CU-01",hu:"HU-001, HU-002",sinRed:"No",papel:"Parc.",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-009",nombre:"Estimado de peajes desglosado por punto",cliente:"A",roles:"ACT-02 ACT-03",cu:"CU-01",hu:"HU-005",sinRed:"No",papel:"No",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-010",nombre:"Señalamiento de tramos inhábiles, sin bloquear",cliente:"A",roles:"ACT-02",cu:"CU-01, CU-03",hu:"HU-006",sinRed:"No",papel:"No",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-011",nombre:"Envío a autorización con número de expediente y congelamiento",cliente:"A",roles:"ACT-02",cu:"CU-01",hu:"HU-004",sinRed:"No",papel:"No",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-012",nombre:"Registro de salida de emergencia para convalidación posterior",cliente:"A",roles:"ACT-02 ACT-10",cu:"CU-01",hu:"HU-008",sinRed:"No",papel:"Parc.",seccion:"2.2 M-06 Solicitud de transporte"},
  {id:"PT-013",nombre:"Bandeja de autorización",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-009, HU-012",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-014",nombre:"Expediente en decisión, en una sola pantalla",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-009, HU-011",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-015",nombre:"Autorizar con constancia inmutable",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-011, HU-015",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-016",nombre:"Rechazar con motivo y solicitud vinculada",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-014",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-017",nombre:"Devolver para corrección con versionado",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-013",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-018",nombre:"Escalamiento de autorización por nivel o umbral",cliente:"A",roles:"ACT-03 ACT-08",cu:"CU-02",hu:"HU-012",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-019",nombre:"Autorización por delegación de firma vigente",cliente:"A",roles:"ACT-03",cu:"CU-02",hu:"HU-015",sinRed:"No",papel:"No",seccion:"2.3 M-06 Autorización"},
  {id:"PT-020",nombre:"Trámite del permiso de circulación en día u hora inhábil",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-03",hu:"HU-016",sinRed:"No",papel:"Sí",seccion:"2.4 M-04 / M-15 Permiso de circulación en día u hora inhábil"},
  {id:"PT-021",nombre:"Firma del permiso por la máxima autoridad (dos toques, celular)",cliente:"A",roles:"ACT-09",cu:"CU-03",hu:"HU-016",sinRed:"No",papel:"No",seccion:"2.4 M-04 / M-15 Permiso de circulación en día u hora inhábil"},
  {id:"PT-022",nombre:"Firma en lote de feriado largo con reporte previo",cliente:"A",roles:"ACT-09",cu:"CU-03",hu:"HU-020",sinRed:"No",papel:"No",seccion:"2.4 M-04 / M-15 Permiso de circulación en día u hora inhábil"},
  {id:"PT-023",nombre:"Emisión e impresión del salvoconducto",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-03, CU-05",hu:"HU-017",sinRed:"No",papel:"Sí",seccion:"2.4 M-04 / M-15 Permiso de circulación en día u hora inhábil"},
  {id:"PT-024",nombre:"Reemisión del permiso por cambio de elementos amparados",cliente:"A",roles:"ACT-04",cu:"CU-03, CU-07",hu:"HU-018",sinRed:"No",papel:"Sí",seccion:"2.4 M-04 / M-15 Permiso de circulación en día u hora inhábil"},
  {id:"PT-025",nombre:"Cola de programación con caducidad de la aprobación",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-04",hu:"HU-021",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-026",nombre:"Asignación de vehículo: compatibilidad, documentación y estado",cliente:"A",roles:"ACT-04",cu:"CU-04",hu:"HU-022, HU-023, HU-024",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-027",nombre:"Declaración de quien conduce: motorista titular y relevos",cliente:"A",roles:"ACT-04",cu:"CU-04",hu:"HU-025, HU-026",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-028",nombre:"Rechazo por licencia no habilitante",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-04, CU-18",hu:"HU-025, HU-108",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-029",nombre:"Reserva exclusiva y conflicto con su titular",cliente:"A",roles:"ACT-04",cu:"CU-04",hu:"HU-027",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-030",nombre:"Consolidación de solicitudes compatibles",cliente:"A",roles:"ACT-04",cu:"CU-04",hu:"HU-030",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-031",nombre:"Constancia probatoria de las verificaciones practicadas",cliente:"A",roles:"ACT-04 ACT-12",cu:"CU-04",hu:"HU-028",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-032",nombre:"Sustitución de vehículo o motorista en PROGRAMADA",cliente:"A",roles:"ACT-04",cu:"CU-07",hu:"HU-043",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-033",nombre:"Sustitución con la misión ya DESPACHADA",cliente:"A",roles:"ACT-04",cu:"CU-07",hu:"HU-044",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-138",nombre:"Compatibilidad de personas externas con personal y carga",cliente:"A",roles:"ACT-04",cu:"CU-04",hu:"HU-125",sinRed:"No",papel:"No",seccion:"2.5 M-07 Programación y asignación"},
  {id:"PT-034",nombre:"Vista previa con folio reservado, marcada «no válida»",cliente:"A",roles:"ACT-04",cu:"CU-05",hu:"HU-029",sinRed:"No",papel:"Sí",seccion:"2.6 M-15 Emisión de documentos"},
  {id:"PT-035",nombre:"Emisión del juego documental: orden de misión, peajes, advertencias, bitácora",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-05",hu:"HU-031, HU-032, HU-033, HU-034, HU-081",sinRed:"No",papel:"Sí",seccion:"2.6 M-15 Emisión de documentos"},
  {id:"PT-036",nombre:"Reimpresión con el mismo folio y marca de reimpresión",cliente:"A",roles:"ACT-04",cu:"CU-05",hu:"HU-036",sinRed:"No",papel:"Sí",seccion:"2.6 M-15 Emisión de documentos"},
  {id:"PT-037",nombre:"Emisión anticipada para delegación sin cobertura",cliente:"A/C",roles:"ACT-10",cu:"CU-05",hu:"HU-037",sinRed:"Sí",papel:"Sí",seccion:"2.6 M-15 Emisión de documentos"},
  {id:"PT-038",nombre:"Tablero de despacho del día: salidas y retornos previstos",cliente:"A",roles:"ACT-05",cu:"CU-06, CU-10",hu:"HU-038",sinRed:"Deg.",papel:"No",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-039",nombre:"Acto de despacho: revalidación, kilometraje de salida e inspección",cliente:"A",roles:"ACT-05",cu:"CU-06",hu:"HU-038, HU-039",sinRed:"Deg.",papel:"Sí",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-040",nombre:"Acta de entrega y traslado de custodia",cliente:"A/C",roles:"ACT-05 ACT-13",cu:"CU-06",hu:"HU-040",sinRed:"Sí",papel:"Sí",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-041",nombre:"Entrega del fondo contra firma, en el acto del despacho",cliente:"A/C",roles:"ACT-07 (ACT-05) ⚠ #26",cu:"CU-06, CU-13",hu:"HU-041, HU-079",sinRed:"Sí",papel:"Sí",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-042",nombre:"Registro del retorno y cierre de la bitácora",cliente:"A/C",roles:"ACT-05 ACT-10",cu:"CU-10",hu:"HU-062, HU-063",sinRed:"Sí",papel:"Sí",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-043",nombre:"Retorno sin vehículo: el bien queda resguardado en sitio",cliente:"A",roles:"ACT-05 ACT-04",cu:"CU-10",hu:"HU-065",sinRed:"Deg.",papel:"No",seccion:"2.7 M-07 / M-08 Despacho y retorno"},
  {id:"PT-044",nombre:"Solicitud del fondo de combustible del período",cliente:"A",roles:"ACT-04",cu:"CU-12",hu:"HU-071",sinRed:"No",papel:"Sí",seccion:"2.8 M-09 Combustible"},
  {id:"PT-045",nombre:"Aprobación del fondo contra cuota y partida",cliente:"A",roles:"ACT-08",cu:"CU-12",hu:"HU-072, HU-073",sinRed:"No",papel:"No",seccion:"2.8 M-09 Combustible"},
  {id:"PT-046",nombre:"Ampliación del fondo agotado y resolución de la prelación",cliente:"A",roles:"ACT-04 ACT-08",cu:"CU-12",hu:"HU-075",sinRed:"No",papel:"No",seccion:"2.8 M-09 Combustible"},
  {id:"PT-047",nombre:"Emisión de la asignación de combustible con folio",cliente:"A",roles:"ACT-07",cu:"CU-13",hu:"HU-076, HU-077, HU-078",sinRed:"No",papel:"Sí",seccion:"2.8 M-09 Combustible"},
  {id:"PT-048",nombre:"Entrega del fondo y registro de su custodia",cliente:"A",roles:"ACT-07",cu:"CU-13",hu:"HU-074",sinRed:"No",papel:"Sí",seccion:"2.8 M-09 Combustible"},
  {id:"PT-049",nombre:"Anulación de la asignación con acta",cliente:"A",roles:"ACT-07",cu:"CU-13",hu:"HU-080",sinRed:"No",papel:"Sí",seccion:"2.8 M-09 Combustible"},
  {id:"PT-050",nombre:"Ciclo de vida del vale y arqueo del fondo",cliente:"A",roles:"ACT-07",cu:"CU-13, CU-15",hu:"HU-074, HU-079, HU-080",sinRed:"No",papel:"No",seccion:"2.8 M-09 Combustible"},
  {id:"PT-051",nombre:"Declaración de la fuente de todo abastecimiento y unicidad del comprobante",cliente:"A",roles:"ACT-07 ACT-04",cu:"CU-14, CU-15",hu:"HU-083, HU-087",sinRed:"No",papel:"No",seccion:"2.8 M-09 Combustible"},
  {id:"PT-052",nombre:"Panel de sincronización de dispositivos",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-11",hu:"HU-066, HU-067",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-053",nombre:"Cola de conflictos",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-11",hu:"HU-068",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-054",nombre:"Comparador de dos versiones lado a lado",cliente:"A",roles:"ACT-04 ACT-10",cu:"CU-11",hu:"HU-068",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-055",nombre:"Resolución por lote con criterio declarado",cliente:"A",roles:"ACT-04",cu:"CU-11",hu:"HU-068",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-056",nombre:"Estado del espejo de ARGOS y Talento Humano",cliente:"A",roles:"ACT-01 ACT-04",cu:"CU-11",hu:"HU-069",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-057",nombre:"Registro de campo que llega después del cierre de la bitácora",cliente:"A",roles:"ACT-04",cu:"CU-11",hu:"HU-070",sinRed:"No",papel:"No",seccion:"2.9 M-16 Sincronización y conflictos"},
  {id:"PT-058",nombre:"Tablero de seguimiento en ruta, con antigüedad del dato",cliente:"A",roles:"ACT-04",cu:"CU-08",hu:"HU-057",sinRed:"No",papel:"No",seccion:"2.10 M-19 Seguimiento en ruta"},
  {id:"PT-059",nombre:"Detalle de la misión en ruta con sus hitos",cliente:"A",roles:"ACT-04 ACT-05",cu:"CU-08",hu:"HU-047, HU-055",sinRed:"No",papel:"No",seccion:"2.10 M-19 Seguimiento en ruta"},
  {id:"PT-060",nombre:"Ampliación del alcance autorizado, con versionado",cliente:"A",roles:"ACT-04 ACT-03",cu:"CU-08, CU-09",hu:"HU-055",sinRed:"No",papel:"No",seccion:"2.10 M-19 Seguimiento en ruta"},
  {id:"PT-061",nombre:"Recepción de la interrupción y resolución de su desenlace",cliente:"A",roles:"ACT-04",cu:"CU-09",hu:"HU-058, HU-059, HU-060",sinRed:"No",papel:"No",seccion:"2.10 M-19 Seguimiento en ruta"},
  {id:"PT-062",nombre:"Relevo de motorista en ruta: resolución desde oficina",cliente:"A",roles:"ACT-04",cu:"CU-09, CU-07",hu:"HU-045, HU-061",sinRed:"No",papel:"Parc.",seccion:"2.10 M-19 Seguimiento en ruta"},
  {id:"PT-063",nombre:"Cola de liquidación, con lo que bloquea cada misión",cliente:"A",roles:"ACT-04",cu:"CU-15",hu:"HU-091",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-064",nombre:"Conciliación galonaje contra kilometraje",cliente:"A",roles:"ACT-04",cu:"CU-15",hu:"HU-088, HU-084",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-065",nombre:"Conciliación del fondo: sobrante y faltante tipificados",cliente:"A",roles:"ACT-04",cu:"CU-15",hu:"HU-089",sinRed:"No",papel:"Parc.",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-066",nombre:"Conciliación de peajes punto por punto",cliente:"A",roles:"ACT-04",cu:"CU-15",hu:"HU-090, HU-086",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-067",nombre:"Bloqueo de la liquidación por segregación de funciones",cliente:"A",roles:"ACT-04 ACT-07",cu:"CU-15",hu:"HU-091",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-068",nombre:"Cadena de trazabilidad y propuesta de cierre",cliente:"A",roles:"ACT-04",cu:"CU-15",hu:"HU-092",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-069",nombre:"Cierre de la misión con la cadena completa",cliente:"A",roles:"ACT-08",cu:"CU-16",hu:"HU-093",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-070",nombre:"Cierre con hallazgo tipificado",cliente:"A",roles:"ACT-08",cu:"CU-16",hu:"HU-094",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-071",nombre:"Hallazgo posterior sobre misión CERRADA — expediente nuevo, sin reapertura",cliente:"A",roles:"ACT-08 ACT-12",cu:"CU-16",hu:"HU-095",sinRed:"No",papel:"No",seccion:"2.11 M-13 Liquidación y cierre"},
  {id:"PT-072",nombre:"Padrón de flota con estado operativo",cliente:"A",roles:"ACT-04 ACT-14",cu:"CU-17",hu:"HU-102",sinRed:"No",papel:"No",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-073",nombre:"Expediente del vehículo: vista completa del ciclo de vida",cliente:"A",roles:"ACT-04 ACT-14 ACT-11",cu:"CU-17",hu:"HU-096 – HU-104",sinRed:"No",papel:"No",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-074",nombre:"Alta del vehículo con título de tenencia",cliente:"A",roles:"ACT-14",cu:"CU-17",hu:"HU-096",sinRed:"No",papel:"Sí",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-075",nombre:"Placa y estado de la lámina (sin placa es estado válido)",cliente:"A",roles:"ACT-14 ACT-04",cu:"CU-17",hu:"HU-097",sinRed:"No",papel:"No",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-076",nombre:"Ficha técnica que habilita: peso bruto, ejes, capacidad",cliente:"A",roles:"ACT-04",cu:"CU-17",hu:"HU-098",sinRed:"No",papel:"Parc.",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-077",nombre:"Tarjeta de responsabilidad y traspaso de custodia",cliente:"A",roles:"ACT-14 ACT-13",cu:"CU-17",hu:"HU-099",sinRed:"No",papel:"Sí",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-078",nombre:"Vencimientos documentales y alertas dirigidas al puesto",cliente:"A",roles:"ACT-04",cu:"CU-17",hu:"HU-101",sinRed:"No",papel:"No",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-079",nombre:"Habilitación del vehículo para operar en flota",cliente:"A",roles:"ACT-04",cu:"CU-17",hu:"HU-102",sinRed:"No",papel:"No",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-080",nombre:"Descargo del bien propio con acta y resolución",cliente:"A",roles:"ACT-14",cu:"CU-17",hu:"HU-103",sinRed:"No",papel:"Sí",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-081",nombre:"Retiro de flota de un bien ajeno (comodato, alquiler)",cliente:"A",roles:"ACT-14",cu:"CU-17",hu:"HU-104",sinRed:"No",papel:"Sí",seccion:"2.12 M-03 / M-04 Flota y expediente del vehículo"},
  {id:"PT-082",nombre:"Padrón de motoristas con su habilitación vigente",cliente:"A",roles:"ACT-04",cu:"CU-18",hu:"HU-105, HU-107",sinRed:"No",papel:"No",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-083",nombre:"Captura de la licencia como dato propio de SIGTI, con fotografía",cliente:"A",roles:"ACT-04",cu:"CU-18",hu:"HU-105",sinRed:"No",papel:"Parc.",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-084",nombre:"Tipos de vehículo habilitados, derivados de la categoría",cliente:"A",roles:"ACT-04",cu:"CU-18",hu:"HU-106",sinRed:"No",papel:"No",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-085",nombre:"Vigencia de la habilitación y alertas anticipadas",cliente:"A",roles:"ACT-04",cu:"CU-18",hu:"HU-107",sinRed:"No",papel:"No",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-086",nombre:"Declaración de conductor fuera del padrón, con el mismo rigor",cliente:"A",roles:"ACT-04",cu:"CU-18, CU-04",hu:"HU-109, HU-108",sinRed:"No",papel:"No",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-087",nombre:"Inhabilitación con causa y encaminamiento de las misiones afectadas",cliente:"A",roles:"ACT-04",cu:"CU-18",hu:"HU-110",sinRed:"No",papel:"No",seccion:"2.13 M-05 Motoristas y habilitación"},
  {id:"PT-088",nombre:"Consulta de la pista de auditoría",cliente:"A",roles:"ACT-12",cu:"CU-16",hu:"—",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-089",nombre:"Rastro del expediente de extremo a extremo, con sus huecos visibles",cliente:"A",roles:"ACT-12",cu:"CU-16",hu:"HU-092",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-090",nombre:"Exportación del paquete de evidencia (PDF con índice, anexos, hoja de cálculo)",cliente:"A",roles:"ACT-12 ACT-08",cu:"CU-16",hu:"—",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-091",nombre:"Reporte de intentos bloqueados por segregación de funciones",cliente:"A",roles:"ACT-12 ACT-08",cu:"CU-02, CU-06, CU-15",hu:"HU-010, HU-039, HU-091",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-092",nombre:"Histórico de cambios de parámetros normativos con vigencia",cliente:"A",roles:"ACT-12",cu:"⛔ falta CU-19",hu:"⛔ sin historia",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-093",nombre:"Registro de consultas a datos de personas externas",cliente:"A",roles:"ACT-12",cu:"CU-16",hu:"HU-118",sinRed:"No",papel:"No",seccion:"2.14 M-14 Auditoría y reportes"},
  {id:"PT-094",nombre:"Manifiesto de personas trasladadas — datos mínimos autorizados",cliente:"A/C",roles:"ACT-02 ACT-04 ACT-05",cu:"CU-01, CU-05, CU-06",hu:"HU-111",sinRed:"Sí",papel:"Sí",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-095",nombre:"Consulta del manifiesto bajo necesidad de conocer, con registro",cliente:"A/C",roles:"ACT-05 ACT-06 ACT-12",cu:"CU-06, CU-08",hu:"HU-117, HU-118, HU-120",sinRed:"Sí",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-128",nombre:"Fundamentación del campo sensible: base legal y necesidad operativa",cliente:"A",roles:"ACT-01",cu:"⛔ falta CU-19",hu:"HU-112",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-129",nombre:"Persona sin documento de identidad: identificación alternativa o no identificada",cliente:"A/C",roles:"ACT-05 (ACT-02)",cu:"CU-01, CU-06",hu:"HU-113",sinRed:"Sí",papel:"Parc.",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-130",nombre:"Cierre del manifiesto al despachar y lista de abordo impresa",cliente:"A/C",roles:"ACT-05",cu:"CU-06",hu:"HU-114",sinRed:"Sí",papel:"Sí",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-131",nombre:"Novedad del manifiesto en ruta: no se presentó, subió, bajó antes",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-116",sinRed:"Sí",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-132",nombre:"Alcance de visibilidad del manifiesto por necesidad de conocer",cliente:"A",roles:"ACT-01 (ACT-03)",cu:"⛔ falta CU-19",hu:"HU-117",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-133",nombre:"Reporte de accesos a manifiestos y alerta de patrón anómalo",cliente:"A",roles:"ACT-12",cu:"CU-16",hu:"HU-119",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-134",nombre:"Hábeas data: buscar todo lo guardado sobre una persona y exportarlo",cliente:"A",roles:"ACT-12 [C]",cu:"CU-16",hu:"HU-121",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-135",nombre:"Rectificación por hábeas data sin destruir el asiento original",cliente:"A",roles:"ACT-12 [C]",cu:"CU-16",hu:"HU-122",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-136",nombre:"Exportación de transparencia sin ningún dato personal",cliente:"A",roles:"ACT-08 [C]",cu:"CU-16",hu:"HU-123",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-137",nombre:"Depuración al vencer el plazo, con aviso previo y verificación de la cadena",cliente:"A",roles:"ACT-01 (ACT-12)",cu:"⛔ falta CU-19",hu:"HU-124",sinRed:"No",papel:"No",seccion:"2.15 M-17 Traslado de personas externas"},
  {id:"PT-096",nombre:"Usuarios, puestos y asignaciones vigentes",cliente:"A",roles:"ACT-01",cu:"⛔ falta CU-19",hu:"⛔ sin historia",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-097",nombre:"Asignación puesto↔rol con control de acumulación incompatible",cliente:"A",roles:"ACT-01 (ACT-08)",cu:"⛔ falta CU-19",hu:"HU-010",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-098",nombre:"Catálogos maestros (M-02)",cliente:"A",roles:"ACT-01 (ACT-08)",cu:"⛔ falta CU-19",hu:"⛔ sin historia",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-099",nombre:"Carga del parámetro normativo con vigencia y respaldo documental",cliente:"A",roles:"ACT-01",cu:"⛔ falta CU-19",hu:"",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-100",nombre:"Puesta en vigencia — doble control",cliente:"A",roles:"ACT-08",cu:"⛔ falta CU-19",hu:"·",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-101",nombre:"Panel de salud: qué está mal y qué hacer",cliente:"A",roles:"ACT-01",cu:"—",hu:"",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-102",nombre:"Respaldo y restauración para alguien sin especialización",cliente:"A",roles:"ACT-01",cu:"—",hu:"",sinRed:"No",papel:"No",seccion:"2.16 M-01 / M-02 Administración y operación"},
  {id:"PT-103",nombre:"Ingreso sin red contra las credenciales del paquete de misión",cliente:"C",roles:"ACT-06 ACT-10",cu:"CU-08",hu:"HU-046",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-104",nombre:"Mi misión — raíz del motorista en el cliente de campo",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-046",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-105",nombre:"Registro en ruta: llegué, salí, estoy esperando",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-047",sinRed:"Sí",papel:"Parc.",seccion:"3 Cliente de campo"},
  {id:"PT-106",nombre:"Entrega de carga y de personas en ruta: quién recibe, con evidencia",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-048, HU-115",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-107",nombre:"Paso por caseta de peaje",cliente:"C",roles:"ACT-06",cu:"CU-14",hu:"HU-049, HU-085",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-108",nombre:"Discrepancia de peaje y reclamo",cliente:"C",roles:"ACT-06",cu:"CU-14",hu:"HU-050, HU-086",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-109",nombre:"Abastecimiento de combustible con comprobante",cliente:"C",roles:"ACT-06",cu:"CU-14",hu:"HU-051, HU-082, HU-083",sinRed:"Sí",papel:"Parc.",seccion:"3 Cliente de campo"},
  {id:"PT-110",nombre:"Consumo sin comprobante y gasto imprevisto",cliente:"C",roles:"ACT-06",cu:"CU-14",hu:"HU-052, HU-087",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-111",nombre:"Aviso de odómetro menor a la última lectura conocida",cliente:"C",roles:"ACT-06",cu:"CU-08, CU-14",hu:"HU-053",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-112",nombre:"Pendientes de envío y adjuntos en espera",cliente:"C",roles:"ACT-06 ACT-10",cu:"CU-11",hu:"HU-054",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-113",nombre:"Solicitud de ampliación del alcance autorizado desde la ruta",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-055",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-114",nombre:"Respaldo en papel: hoja de bitácora con folio",cliente:"C",roles:"ACT-06 ACT-10",cu:"CU-08",hu:"HU-056",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-115",nombre:"Actualización de estado y última posición conocida",cliente:"C",roles:"ACT-06",cu:"CU-08",hu:"HU-057",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-116",nombre:"Registro de interrupción en ruta — avería, accidente, robo, otra",cliente:"C",roles:"ACT-06",cu:"CU-09",hu:"HU-058",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-117",nombre:"Desenlace de la interrupción, comunicado al motorista",cliente:"C",roles:"ACT-06",cu:"CU-09",hu:"HU-060",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-118",nombre:"Relevo de motorista en ruta con acta y corte de odómetro",cliente:"C",roles:"ACT-06",cu:"CU-09, CU-07",hu:"HU-045, HU-061",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-119",nombre:"Retorno y cierre de la bitácora desde el campo",cliente:"C",roles:"ACT-06 ACT-10",cu:"CU-10",hu:"HU-062, HU-065",sinRed:"Sí",papel:"Parc.",seccion:"3 Cliente de campo"},
  {id:"PT-120",nombre:"Estado de sincronización del dispositivo",cliente:"C",roles:"ACT-06 ACT-10",cu:"CU-11",hu:"HU-066, HU-067",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-121",nombre:"Registro de la salida sin conectividad, en el predio",cliente:"C",roles:"ACT-05 ACT-10 ⚠ #26",cu:"CU-06",hu:"HU-042",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-122",nombre:"Captura de solicitud en delegación sin red",cliente:"C",roles:"ACT-10",cu:"CU-01",hu:"HU-007",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-123",nombre:"Digitación diferida desde el papel, con foto del original",cliente:"C",roles:"ACT-10",cu:"CU-11, CU-10",hu:"HU-064, HU-007",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-124",nombre:"Constatación de la identificación institucional del vehículo",cliente:"C",roles:"ACT-14 (ACT-13)",cu:"CU-17",hu:"HU-100",sinRed:"Sí",papel:"Sí",seccion:"3 Cliente de campo"},
  {id:"PT-125",nombre:"Consulta de mis documentos: orden de misión y salvoconducto",cliente:"C",roles:"ACT-06",cu:"CU-08, CU-03",hu:"HU-017, HU-019",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-127",nombre:"Mi delegación hoy — raíz de ACT-10 · misiones, pendientes, papeles por digitar",cliente:"C",roles:"ACT-10",cu:"CU-01, CU-10, CU-11",hu:"HU-007, HU-064, HU-066",sinRed:"Sí",papel:"No",seccion:"3 Cliente de campo"},
  {id:"PT-126",nombre:"Verificación del documento por QR — mínimo verificable, nunca el expediente",cliente:"P",roles:"ACT-15 sin autenticar",cu:"CU-03, CU-05",hu:"HU-019, HU-035",sinRed:"No",papel:"No",seccion:"4 Superficie pública"},
];
