// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sigti.Datos;

#nullable disable

namespace Sigti.Datos.Migraciones
{
    [DbContext(typeof(SigtiDbContext))]
    [Migration("20260827235205_CustodiaDeVehiculo")]
    partial class CustodiaDeVehiculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sigti.Datos.FilaDeAdjunto", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("IdTransicion")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("RecibidoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Clasificacion");

                    b.HasIndex("IdTransicion");

                    b.ToTable("Adjunto", "mision");
                });

            modelBuilder.Entity("Sigti.Datos.FilaDeAsignacionDePuesto", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("ConfirmadoAlUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Persona");

                    b.HasIndex("Puesto");

                    b.ToTable("AsignacionDePuestoEspejo", "organizacion");
                });

            modelBuilder.Entity("Sigti.Datos.FilaDeConductor", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("EsDelPadron")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NumeroDeLicencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Restricciones")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateOnly>("VenceLicencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDeLicencia")
                        .IsUnique();

                    b.HasIndex("VenceLicencia");

                    b.ToTable("Conductor", "motoristas");
                });

            modelBuilder.Entity("Sigti.Datos.FilaDeCustodia", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Acta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Custodio")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<byte[]>("VehiculoId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Custodia", "flota");
                });

            modelBuilder.Entity("Sigti.Datos.FilaDeVehiculo", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IdentificacionInstitucionalVerificada")
                        .HasColumnType("bit");

                    b.Property<bool>("LlevaRemolque")
                        .HasColumnType("bit");

                    b.Property<int>("PesoBrutoKg")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("TieneConstanciaSustitutaDePlaca")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDeVehiculo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly>("VenceMatricula")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VencePoliza")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VenceRevisionMecanica")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Siglas")
                        .IsUnique();

                    b.HasIndex("VenceMatricula");

                    b.ToTable("Vehiculo", "flota");
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CapturadaPor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HolguraDias")
                        .HasColumnType("int");

                    b.Property<string>("ObjetoDelTraslado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Retorno")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Salida")
                        .HasColumnType("date");

                    b.Property<string>("SolicitanteDeDerecho")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Expediente", "mision");
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeTransicion", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("ConductorTomado")
                        .HasColumnType("binary(16)");

                    b.Property<int>("DesfaseMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Ejecuta")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("ExpedienteId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("IdDeCaptura")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("MomentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Transicion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("VehiculoTomado")
                        .HasColumnType("binary(16)");

                    b.HasKey("Id");

                    b.HasIndex("IdDeCaptura")
                        .IsUnique()
                        .HasFilter("[IdDeCaptura] IS NOT NULL");

                    b.HasIndex("VehiculoTomado")
                        .HasFilter("[VehiculoTomado] IS NOT NULL");

                    b.HasIndex("ExpedienteId", "Orden")
                        .IsUnique();

                    b.ToTable("Transicion", "mision");
                });

            modelBuilder.Entity("Sigti.Dominio.Bitacora.Asiento", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Cola")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DesfaseMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("MomentoRecibidoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MomentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Secuencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Cola", "Secuencia")
                        .IsUnique();

                    b.ToTable("Asiento", "bitacora");
                });

            modelBuilder.Entity("Sigti.Dominio.M02_Parametros.VersionDeParametro", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("AprobadoPor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CargadoPor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("RegistradoDesde")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RegistradoHasta")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Respaldo", "Sigti.Dominio.M02_Parametros.VersionDeParametro.Respaldo#RespaldoDocumental", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Adjunto")
                                .IsRequired()
                                .HasColumnType("binary(16)")
                                .HasColumnName("RespaldoAdjunto");

                            b1.Property<DateOnly>("FechaDeVerificacion")
                                .HasColumnType("date")
                                .HasColumnName("RespaldoVerificadoEl");

                            b1.Property<string>("Fuente")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)")
                                .HasColumnName("RespaldoFuente");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Clave", "VigenteDesde");

                    b.ToTable("VersionDeParametro", "catalogo");
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeTransicion", b =>
                {
                    b.HasOne("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", null)
                        .WithMany("Transiciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", b =>
                {
                    b.Navigation("Transiciones");
                });
#pragma warning restore 612, 618
        }
    }
}
