// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sigti.Datos;

#nullable disable

namespace Sigti.Datos.Migraciones
{
    [DbContext(typeof(SigtiDbContext))]
    [Migration("20260826201408_ParametrosNormativos")]
    partial class ParametrosNormativos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("CapturadaPor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SolicitanteDeDerecho")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Expediente", "mision");
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeTransicion", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("DesfaseMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Ejecuta")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("ExpedienteId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("MomentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Transicion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId", "Orden")
                        .IsUnique();

                    b.ToTable("Transicion", "mision");
                });

            modelBuilder.Entity("Sigti.Dominio.Bitacora.Asiento", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Cola")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DesfaseMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("MomentoRecibidoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MomentoUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Secuencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Cola", "Secuencia")
                        .IsUnique();

                    b.ToTable("Asiento", "bitacora");
                });

            modelBuilder.Entity("Sigti.Dominio.M02_Parametros.VersionDeParametro", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("AprobadoPor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CargadoPor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("RegistradoDesde")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RegistradoHasta")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Clave", "VigenteDesde");

                    b.ToTable("VersionDeParametro", "catalogo");
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeTransicion", b =>
                {
                    b.HasOne("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", null)
                        .WithMany("Transiciones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sigti.Datos.M07_ProgramacionYDespacho.FilaDeExpediente", b =>
                {
                    b.Navigation("Transiciones");
                });
#pragma warning restore 612, 618
        }
    }
}
